name: "Conftest Push"
description: "Push an OPA bundle to an OCI-compliant registry"
author: "Chuck D'Antonio"
branding:
  icon: "upload"
  color: "blue"
inputs: 
  path:
    description: "Path to include in the bundle"
    default: "." 
  policy:
    description: "Where to find the policy folder or file"
    default: "policy"
  repository:
    description: "Repository for the policy on an OCI-compliant registry supporting OPA bundles"
    required: true
runs:
  using: 'docker'
  image: 'docker://instrumenta/conftest:latest'
  entrypoint: sh
  args:
  - -c
  - |
    conftest push --policy "${{ inputs.policy }}" "${{ inputs.repository }}:${{ inputs.tag }}" "${{ inputs.path }}" 
