name: Release

on: push

jobs:
  test:
    name: Unit test the policies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Verify policies
        uses: ./.github/actions/conftest-verify
          
  release:
    name: Release the OPA bundle
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to registry
        run: |
          cp -r ${HOME}/.docker /home/runner/work/_temp/_github_home/
        uses: ./.github/actions/conftest-push
        with:
          repository: ghcr.io/crdant/cf-manifest-policy
