name: Test Pull Request

on: [ pull_request ]

jobs:
  test:
    name: Unit test policies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        id: checkout
        uses: actions/checkout@v2
      - name: Verify Policies
        id: verify
        uses: ./.github/actions/conftest-verify
